### ISSUE TITLE
Did this get removed off the chrome store

### ISSUE THREAD

**Issue by mattlima2517** [WillBillChiang/Pinnacle-Grade-Calculator#2]
I was trying to get the link to send to a friend but noticed its a dead link on your page and cant find it on the chrome store, what happened!

**Comment by WillBillChiang** [comment]
The link in the read me appears to be working. 
https://chrome.google.com/webstore/detail/pinnacle-grade-calculator/ajmebljhmdndihimeodajeiicccpdfei?hl=en
